import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Hero(),
        ]),
      ),
    );
  }
}

class Hero extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1440,
          height: 900,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 900,
                child: Container(
                  width: 1440,
                  height: 900,
                  decoration: BoxDecoration(color: Color(0xFFFFFCF4)),
                ),
              ),
              Positioned(
                left: 135,
                top: 150,
                child: Container(
                  width: 570,
                  height: 685,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 470,
                          height: 685,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/470x685"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 570,
                        top: 393,
                        child: Transform(
                          transform: Matrix4.identity()
                            ..translate(0.0, 0.0)
                            ..rotateZ(3.14),
                          child: Container(
                            width: 270,
                            height: 244,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: -270,
                                  top: 0,
                                  child: Container(
                                    width: 270,
                                    height: 244,
                                    decoration: ShapeDecoration(
                                      color: Colors.white,
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(12),
                                      ),
                                      shadows: [
                                        BoxShadow(
                                          color: Color(0x0C000000),
                                          blurRadius: 32,
                                          offset: Offset(0, 16),
                                          spreadRadius: 0,
                                        )
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: -246,
                                  top: 24,
                                  child: Container(
                                    width: 183,
                                    height: 56,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 4,
                                          child: Container(
                                            width: 48,
                                            height: 48,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 0,
                                                  top: 0,
                                                  child: Container(
                                                    width: 48,
                                                    height: 48,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFFF8E7),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 12,
                                                  top: 12,
                                                  child: Container(
                                                    width: 24,
                                                    height: 24,
                                                    clipBehavior:
                                                        Clip.antiAlias,
                                                    decoration: BoxDecoration(),
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 64,
                                          top: 0,
                                          child: Container(
                                            width: 119,
                                            height: 56,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 0,
                                                  top: 26,
                                                  child: Text(
                                                    'UI/UX Design',
                                                    style: TextStyle(
                                                      color: Color(0xFF171000),
                                                      fontSize: 18,
                                                      fontFamily: 'Poppins',
                                                      fontWeight:
                                                          FontWeight.w600,
                                                      height: 0.09,
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 0,
                                                  top: 0,
                                                  child: Text(
                                                    '20 Courses',
                                                    style: TextStyle(
                                                      color: Color(0xFF5F5B53),
                                                      fontSize: 14,
                                                      fontFamily: 'Poppins',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0.13,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: -246,
                                  top: 94,
                                  child: Container(
                                    width: 188,
                                    height: 56,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 4,
                                          child: Container(
                                            width: 48,
                                            height: 48,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 0,
                                                  top: 0,
                                                  child: Container(
                                                    width: 48,
                                                    height: 48,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFBEFFF),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 12,
                                                  top: 12,
                                                  child: Container(
                                                    width: 24,
                                                    height: 24,
                                                    clipBehavior:
                                                        Clip.antiAlias,
                                                    decoration: BoxDecoration(),
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 64,
                                          top: 0,
                                          child: Container(
                                            width: 124,
                                            height: 56,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 0,
                                                  top: 26,
                                                  child: Text(
                                                    'Development',
                                                    style: TextStyle(
                                                      color: Color(0xFF171000),
                                                      fontSize: 18,
                                                      fontFamily: 'Poppins',
                                                      fontWeight:
                                                          FontWeight.w600,
                                                      height: 0.09,
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 0,
                                                  top: 0,
                                                  child: Text(
                                                    '20 Courses',
                                                    style: TextStyle(
                                                      color: Color(0xFF5F5B53),
                                                      fontSize: 14,
                                                      fontFamily: 'Poppins',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0.13,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: -246,
                                  top: 164,
                                  child: Container(
                                    width: 158,
                                    height: 56,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 4,
                                          child: Container(
                                            width: 48,
                                            height: 48,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 0,
                                                  top: 0,
                                                  child: Container(
                                                    width: 48,
                                                    height: 48,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFEBE9FF),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 12,
                                                  top: 12,
                                                  child: Container(
                                                    width: 24,
                                                    height: 24,
                                                    clipBehavior:
                                                        Clip.antiAlias,
                                                    decoration: BoxDecoration(),
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 64,
                                          top: 26,
                                          child: Text(
                                            'Marketing',
                                            style: TextStyle(
                                              color: Color(0xFF171000),
                                              fontSize: 18,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w600,
                                              height: 0.09,
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 64,
                                          top: 0,
                                          child: Text(
                                            '30 Courses',
                                            style: TextStyle(
                                              color: Color(0xFF5F5B53),
                                              fontSize: 14,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w400,
                                              height: 0.13,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 835,
                top: 214,
                child: Container(
                  width: 470,
                  height: 558,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 466,
                        child: Container(
                          width: 361,
                          height: 92,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Recent engagement',
                                  style: TextStyle(
                                    color: Color(0xFF5F5B53),
                                    fontSize: 18,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                    height: 0.09,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 38,
                                child: Text.rich(
                                  TextSpan(
                                    children: [
                                      TextSpan(
                                        text: '50K ',
                                        style: TextStyle(
                                          color: Color(0xFF171000),
                                          fontSize: 44,
                                          fontFamily: 'Sen',
                                          fontWeight: FontWeight.w700,
                                          height: 0.03,
                                        ),
                                      ),
                                      TextSpan(
                                        text: 'Students',
                                        style: TextStyle(
                                          color: Color(0xFF5F5B53),
                                          fontSize: 18,
                                          fontFamily: 'Poppins',
                                          fontWeight: FontWeight.w400,
                                          height: 0.09,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 201,
                                top: 38,
                                child: Text.rich(
                                  TextSpan(
                                    children: [
                                      TextSpan(
                                        text: '70+ ',
                                        style: TextStyle(
                                          color: Color(0xFF171000),
                                          fontSize: 44,
                                          fontFamily: 'Sen',
                                          fontWeight: FontWeight.w700,
                                          height: 0.03,
                                        ),
                                      ),
                                      TextSpan(
                                        text: 'Courses',
                                        style: TextStyle(
                                          color: Color(0xFF5F5B53),
                                          fontSize: 18,
                                          fontFamily: 'Poppins',
                                          fontWeight: FontWeight.w400,
                                          height: 0.09,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 208,
                        top: 366,
                        child: Container(
                          width: 202,
                          height: 40,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 40,
                                  height: 40,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 40,
                                          height: 40,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: OvalBorder(),
                                            shadows: [
                                              BoxShadow(
                                                color: Color(0x11000000),
                                                blurRadius: 16,
                                                offset: Offset(0, 8),
                                                spreadRadius: 0,
                                              )
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 26,
                                        top: 14,
                                        child: Transform(
                                          transform: Matrix4.identity()
                                            ..translate(0.0, 0.0)
                                            ..rotateZ(1.57),
                                          child: Container(
                                            width: 12,
                                            height: 12,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFFFB900),
                                              shape:
                                                  StarBorder.polygon(sides: 3),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 54,
                                top: 5,
                                child: SizedBox(
                                  width: 148,
                                  child: Text(
                                    'Watch Video',
                                    style: TextStyle(
                                      color: Color(0xFF171000),
                                      fontSize: 18,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w600,
                                      height: 0.09,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 354,
                        child: Container(
                          width: 180,
                          height: 64,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 180,
                                  height: 64,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFFFB800),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(32),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 34,
                                top: 17,
                                child: Text(
                                  'See Courses',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 18,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 0.09,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 226,
                        child: SizedBox(
                          width: 470,
                          child: Text(
                            'Build new skills for that “this is my year” feeling with courses, certificates, and degrees from world-class universities and companies.',
                            style: TextStyle(
                              color: Color(0xFF5E5B53),
                              fontSize: 18,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 470,
                          child: Text(
                            'Learn without limits and spread knowledge.',
                            style: TextStyle(
                              color: Color(0xFF171000),
                              fontSize: 58,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.02,
                              letterSpacing: -1.16,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 135,
                top: 36,
                child: Container(
                  width: 1170,
                  height: 49,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 8,
                        child: Text.rich(
                          TextSpan(
                            children: [
                              TextSpan(
                                text: 'Lesson',
                                style: TextStyle(
                                  color: Color(0xFF171000),
                                  fontSize: 24,
                                  fontFamily: 'Sen',
                                  fontWeight: FontWeight.w700,
                                  height: 0.06,
                                ),
                              ),
                              TextSpan(
                                text: '.',
                                style: TextStyle(
                                  color: Color(0xFFFFB900),
                                  fontSize: 24,
                                  fontFamily: 'Sen',
                                  fontWeight: FontWeight.w700,
                                  height: 0.06,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 597,
                        top: 11,
                        child: Container(
                          width: 359,
                          height: 28,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 1,
                                top: 26,
                                child: Container(
                                  width: 12,
                                  height: 2,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF171000),
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(1)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Home',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Color(0xFF171000),
                                    fontSize: 16,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 0.11,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 91,
                                top: 0,
                                child: Text(
                                  'Courses',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Color(0xFF5F5B53),
                                    fontSize: 16,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                    height: 0.11,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 199,
                                top: 0,
                                child: Text(
                                  'Pricing',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Color(0xFF5F5B53),
                                    fontSize: 16,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                    height: 0.11,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 295,
                                top: 0,
                                child: Text(
                                  'Reviews',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Color(0xFF5F5B53),
                                    fontSize: 16,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                    height: 0.11,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1026,
                        top: 0,
                        child: Container(
                          width: 144,
                          height: 49,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 144,
                                  height: 49,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF171000),
                                    shape: RoundedRectangleBorder(
                                      borderRadius:
                                          BorderRadius.circular(24.50),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 41,
                                top: 11,
                                child: Text(
                                  'Sign Up',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 16,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 0.11,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
